### PR TITLE
Adding 1.11 to versions

### PR DESCRIPTION
**Pull request by wolfejw86**
~I'm actually not 100% sure if this is all that's required, but I was trying to add version 1.11 using this base image and noticed it wasn't present yet.~ EDIT: I have updated the PR to include what I believe are all of the required changes.  The main thing I'm missing is where you are publishing to your docker handle - unless you are doing that manually?
If this isn't the right way to add a version feel free to discard this.  Thanks for making an awesome base image either way I enjoyed sifting through the code to see how it worked :)

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
Yeah it's a little more involved, but not much. See https://github.com/disney/meteor-base/pull/41.

**Comment by diavrank** [comment]
Hi, excuse me, how long take to do this? I'm exciting to use this docker image with Meteor 1.11  :)

**Comment by wolfejw86** [comment]
I was planning on applying everything from the reference PR provided above
this evening. After that it will go through what I assume is a fairly quick
review (if I can get it right 😬)
After that it’s whatever the normal process is to push the images to docker
hub for the author 🙂

**Comment by wolfejw86** [comment]
@GeoffreyBooth alrighty - I updated all packages with `meteor update`, updated vulnerable deps in package.json with npm audit + meteor npm install, updated nodejs versions to latest nodejs LTS, and  the dockerfile examples + documentation.  I _think_ this is good to go now - pls let me know if there's anything I missed :)

**Comment by GeoffreyBooth** [comment]
Thanks @wolfejw86, I'll push the new images to Docker Hub within the next day or so (they take a long time to build locally).

If you or anyone else wants to add a section to the README of the steps to add a new version, I would appreciate a PR for that 😄

**Comment by GeoffreyBooth** [comment]
@diavrank They're up now.

**Pull request merged**
