### PR TITLE
feat:added 2.15

### PR DESCRIPTION
**Pull request by bladerunner2020**
- Added support for v2.15
- Removed duplicated lines in supports.sh (there were few duplicated lines for 2.14 version)

PS
It looks like update.sh has an issue while running on MacOS (haven't tested it on linux yet).
build.sh doesn't work on MacOS (tested on linux)

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
> It looks like update.sh has an issue while running on MacOS (haven't tested it on linux yet).
> build.sh doesn’t work on MacOS (tested on linux)

What issues are you seeing? I develop on Mac and I haven’t had issues.

**Comment by bladerunner2020** [comment]
First of all, in the latest version there are duplicated lines as I mentioned in my PR:
Screenshot 2024-03-13 at 07 44 46

**Comment by bladerunner2020** [comment]
When I run `./update.sh --meteor-version 2.15 --node-version 14.21.4` I got multiple lines with 2.15 in support.sh

image

This I got both MacOs and linux.

**Comment by bladerunner2020** [comment]
When I tried to run ./build.sh 2.15 on MacOs I got "Retrying download in 5 seconds..." and then the following error:

```bash
 meteor-base-origin git:(main) ✗ ./build.sh 2.15
Building Docker base image for Meteor 2.15...
[+] Building 58.9s (7/9)                                                                                                                            docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                0.0s
 => => transferring dockerfile: 1.88kB                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                    0.0s
 => [1/5] FROM docker.io/library/ubuntu                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                   0.0s
 => => transferring context: 51.21kB                                                                                                                                0.0s
 => CACHED [2/5] RUN apt-get update &&  apt-get install --assume-yes apt-transport-https ca-certificates &&  apt-get install --assume-yes --no-install-recommends   0.0s
 => ERROR [3/5] RUN curl https://install.meteor.com/?release=2.15 --output /tmp/install-meteor.sh &&  sed --in-place "s/tar -xzf.*/bsdtar -xf "$TARBALL_FILE" -C   58.9s
------
 > [3/5] RUN curl https://install.meteor.com/?release=2.15 --output /tmp/install-meteor.sh &&   sed --in-place "s/tar -xzf.*/bsdtar -xf "$TARBALL_FILE" -C "$INSTALL_TMPDIR"/g" /tmp/install-meteor.sh &&        printf "\n[-] Installing Meteor 2.15...\n\n" &&         sh /tmp/install-meteor.sh:
0.157   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
0.157                                  Dload  Upload   Total   Spent    Left  Speed
100  7817    0  7817    0     0   8375      0 --:--:-- --:--:-- --:--:--  8369
1.114
1.114 [-] Installing Meteor 2.15...
1.114
1.115 This Meteor 2.x version is running on a deprecated Node.js version (14). Meteor 3.0 is in progress, and it will run on the latest Node.js version. For more information, please consult this migration guide: https://guide.meteor.com/3.0-migration.
1.127 Downloading Meteor distribution
2.083 Retrying download in 5 seconds...
7.820 Retrying download in 5 seconds...
13.47 Retrying download in 5 seconds...
19.15 Retrying download in 5 seconds...
25.02 Retrying download in 5 seconds...
30.81 Retrying download in 5 seconds...
36.53 Retrying download in 5 seconds...
42.27 Retrying download in 5 seconds...
48.05 Retrying download in 5 seconds...
53.84 Retrying download in 5 seconds...
------
Dockerfile:20
--------------------
  19 |     # Install Meteor
  20 | >>> RUN curl https://install.meteor.com/?release=$METEOR_VERSION --output /tmp/install-meteor.sh && \
  21 | >>> 	# Replace tar with bsdtar in the install script; https://github.com/jshimko/meteor-launchpad/issues/39 and https://github.com/intel/lkp-tests/pull/51
  22 | >>> 	sed --in-place "s/tar -xzf.*/bsdtar -xf \"\$TARBALL_FILE\" -C \"\$INSTALL_TMPDIR\"/g" /tmp/install-meteor.sh && \
  23 | >>> 	# Install Meteor
  24 | >>> 	printf "\n[-] Installing Meteor $METEOR_VERSION...\n\n" && \
  25 | >>> 	sh /tmp/install-meteor.sh
  26 |
--------------------
ERROR: failed to solve: process "/bin/sh -c curl https://install.meteor.com/?release=$METEOR_VERSION --output /tmp/install-meteor.sh && \tsed --in-place \"s/tar -xzf.*/bsdtar -xf \\\"\\$TARBALL_FILE\\\" -C \\\"\\$INSTALL_TMPDIR\\\"/g\" /tmp/install-meteor.sh && \tprintf \"\\n[-] Installing Meteor $METEOR_VERSION...\\n\\n\" && \tsh /tmp/install-meteor.sh" did not complete successfully: exit code: 1
[+] Building 1.4s (7/9)                                                                                                                             docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                                                                0.0s
 => => transferring dockerfile: 1.88kB                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                    0.0s
 => [1/5] FROM docker.io/library/ubuntu                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                   0.0s
 => => transferring context: 398B                                                                                                                                   0.0s
 => CACHED [2/5] RUN apt-get update &&  apt-get install --assume-yes apt-transport-https ca-certificates &&  apt-get install --assume-yes --no-install-recommends   0.0s
 => CANCELED [3/5] RUN curl https://install.meteor.com/?release=2.15 --output /tmp/install-meteor.sh &&  sed --in-place "s/tar -xzf.*/bsdtar -xf "$TARBALL_FILE" -  1.4s
ERROR: failed to solve: Canceled: context canceled
[+] Building 0.6s (7/9)                                                                                                                             docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                                                                0.0s
 => => transferring dockerfile: 1.88kB                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                    0.0s
 => [1/5] FROM docker.io/library/ubuntu                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                   0.0s
 => => transferring context: 398B                                                                                                                                   0.0s
 => CACHED [2/5] RUN apt-get update &&  apt-get install --assume-yes apt-transport-https ca-certificates &&  apt-get install --assume-yes --no-install-recommends   0.0s
 => CANCELED [3/5] RUN curl https://install.meteor.com/?release=2.15 --output /tmp/install-meteor.sh &&  sed --in-place "s/tar -xzf.*/bsdtar -xf "$TARBALL_FILE" -  0.6s
ERROR: failed to solve: Canceled: context canceled
[+] Building 1.5s (7/9)                                                                                                                             docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                     0.0s
 => [internal] load build definition from Dockerfile                                                                                                                0.0s
 => => transferring dockerfile: 1.88kB                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                    0.0s
 => [1/5] FROM docker.io/library/ubuntu                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                   0.0s
 => => transferring context: 398B                                                                                                                                   0.0s
 => CACHED [2/5] RUN apt-get update &&  apt-get install --assume-yes apt-transport-https ca-certificates &&  apt-get install --assume-yes --no-install-recommends   0.0s
 => CANCELED [3/5] RUN curl https://install.meteor.com/?release=2.15 --output /tmp/install-meteor.sh &&  sed --in-place "s/tar -xzf.*/bsdtar -xf "$TARBALL_FILE" -  1.5s
ERROR: failed to solve: Canceled: context canceled
^CERROR: Get "http://%2FUsers%2Fa.pivovarov%2F.docker%2Frun%2Fdocker.sock/_ping": context canceled
Error building Docker base image for Meteor 2.15
➜  meteor-base-origin git:(main) ✗
```

**Comment by bladerunner2020** [comment]
Though maybe it just issue with slow connection.... Not sure.

**Comment by GeoffreyBooth** [comment]
> When I run `./update.sh --meteor-version 2.15 --node-version 14.21.4` I got multiple lines with 2.15 in support.sh

Do you want to fix this? (In a separate PR.)

As for the errors, I don’t know, that looks like a network error.

**Comment by bladerunner2020** [comment]
I will try to investigate both errors this weekend. Will fix first one.

**Comment by bladerunner2020** [comment]
> > When I run `./update.sh --meteor-version 2.15 --node-version 14.21.4` I got multiple lines with 2.15 in support.sh
> 
> Do you want to fix this? (In a separate PR.)
> 

See #156

**Pull request merged**
