### PR TITLE
useUnifiedTopology warning

### PR DESCRIPTION
**Pull request by martinoosthuizen**
Reconfigured the client connection so that it passes the useUnifiedTopology argument to the constructor as required by v3.6+.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
Do you have something you can cite to explain why `useUnifiedTopology` is required?

And I don’t see why we should make the other changes (Ubuntu, indents).

**Comment by martinoosthuizen** [comment]
Hi @GeoffreyBooth 

> Do you have something you can cite to explain why `useUnifiedTopology` is required?

Mongo itself now issues this warning in the console:

`DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`

I recently upgraded one of our Meteor applications to 1.11.1, Node 12.18.0, running on GKE (1.15.12-gke.2), and this warning started showing up. So it's not critical right now, but you'll need that change at some point. The API reference is not super descriptive, but it's been part of the API since at least 3.3 as far as I can tell https://mongodb.github.io/node-mongodb-native/3.6/api/MongoClient.html

> And I don’t see why we should make the other changes (Ubuntu, indents).

About the indents, my bad, I've got prettier set to format on save in my IDE.

Regarding the Ubuntu change, I should remove that from this PR, two separate issues; it just piled it onto this PR when I did a subsequent commit to master on the fork. But it's worth pointing out an edge case where Alpine is bombing and Ubuntu runs without issues. We have a product that has a backend app running Meteor 1.8 and a customer-facing app running Meteor 1.11.1, but they are both pointing to the same Mongo StatefulSet in the same cluster. So the Docker container kept crashing as soon as the user tried to log in from the customer-facing (Meteor 1.11.1) app. It uses the standard client-side Meteor.loginWithPassword method. The app itself didn't throw any exception, but it was failing at container level with exit code 139. It's so bizarre and I spent a few hours initially trying to debug it. Then earlier today I tried using Ubuntu 18.04, and there's no trace of the issue. I could try dig deeper into the Alpine issue if you're interested, but from my perspective Ubuntu seems to be more reliable to use, and looking at our K8s resource monitor, using Ubuntu 18.04 barely lifted the needle compared to Alpine in the overall resource usage.

**Comment by GeoffreyBooth** [comment]
The `MongoClient` code you modified is only to ping to see if Mongo is up and running. That Node process exits as soon as it gets a successful response back. It has nothing to do with your app and how Meteor connects to Mongo.

With regard to Ubuntu, that’s only used during the build phase. Your app runs in Alpine, unless you’ve changed it. Pinning a particular version of Ubuntu during the build phase shouldn’t make much if any difference.

**Comment by GeoffreyBooth** [comment]
I think there’s no need to change things. Really the issue here is that the Mongo client (the npm module) defaults to the now-deprecated setting, and the Mongo server warns folks to update. All we’re doing with that particular instance of the Mongo client is pinging until the server is up, so the warning can be ignored. I would assume that some future update to the Mongo client will default to the new, non-deprecated setting; maybe that’s already happened, and all you need to do is update the Mongo client in the startup script. Regardless, this doesn’t affect anything; this Mongo client isn’t used as part of your app.

**Pull request closed without merging**
