### PR TITLE
Add 2.8.0

### PR DESCRIPTION
**Pull request by diavrank**
[Changelog](https://github.com/meteor/meteor/blob/devel/docs/history.md#v28-2022-10-19)

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
[CI fails](https://github.com/disney/meteor-base/actions/runs/3309057466/jobs/5461873539) with `./test.sh: line 43: node_version: unbound variable`. You need to add 2.8.0 to the end of https://github.com/disney/meteor-base/blob/main/support.sh.

Did you use https://github.com/disney/meteor-base/blob/main/update.sh? If so, it needs to be fixed to update `support.sh`.

**Comment by diavrank** [comment]
Hi, yes, I used the update.sh script to update the files. It's weird why it didn't update the support.sh file.

**Comment by diavrank** [comment]
it's throwing this error now:

````shell
Testing Docker image geoffreybooth/meteor-base:2.5.7...
Creating test app...
Building test app Docker image...
Launching test app...
mongo Pulling 
mongo Error 
Error response from daemon: Head "https://registry-1.docker.io/v2/library/mongo/manifests/latest": unknown: failed query public repo scope sets: unable to complete public repo access query from database: dial tcp 10.1.47.73:5432: connect: connection refused
Error: Process completed with exit code 1[8](https://github.com/disney/meteor-base/actions/runs/3313938616/jobs/5472578508#step:4:9).
````
any suggestion to fix it?

**Comment by GeoffreyBooth** [comment]
> any suggestion to fix it?

That looks like a network error prevented the download of the `mongo` image. I’ll just retry.

**Comment by GeoffreyBooth** [comment]
> Hi, yes, I used the update.sh script to update the files. It’s weird why it didn’t update the support.sh file.

I bet I forgot to include that in `update.sh` because when I wrote `update.sh`, the Node version hadn’t changed in a while. If you have time, it would be nice to fix the script to that it updates `support.sh` properly. (In a separate PR.)

**Comment by diavrank** [comment]
Sure! I will check it out today later.

Where can I run again the test for 2.2.3? It seems that it was canceled but I don't know why.

**Comment by wolasss** [comment]
@GeoffreyBooth Could you publish the image to dockerhub? Thanks :)

**Comment by GeoffreyBooth** [comment]
Updated.

**Pull request merged**
