### PR TITLE
Add 2.5.1

### PR DESCRIPTION
**Pull request by diavrank**
Changelog: [Mac M1 Support](https://github.com/meteor/meteor/blob/devel/History.md#v251-2021-11-17)

### CODE REVIEW

**Comment by diavrank** [comment]
Hi, I have just realized that tests failed with v2.51. I'm not sure how to solve it. 

Can you give me a hand?

**Comment by GeoffreyBooth** [comment]
You can see the error here: https://github.com/disney/meteor-base/runs/4275825609?check_suite_focus=true

It’s when trying to build `example/app-with-native-dependencies.dockerfile`. It errors on the instruction `RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh`. The error is saying that it’s trying to compile Fibers but it can’t because it can’t find Python.

Fibers shouldn’t need to be built, because Alpine-compatible binaries are published with it. Perhaps the newer Node docker image has a newer Alpine that isn’t compatible with the binaries included in Fibers, and therefore no acceptable prebuilt binary is found and therefore Node tries to create a new one. Even still, it shouldn’t fail when trying to do so, because the dependencies for compilation are present in this image. I don’t have time to dig any deeper right now, but I’d think you should be able to reproduce this yourself locally in the 2.5.1 branch by going into the `example` folder and running `docker build --file ./app-with-native-dependencies.dockerfile .`.

**Comment by diavrank** [comment]
Hi, sorry for the delay, I have had a lot of work this month, so, it is going to be a bit complicated for me to follow up on this issue. Maybe, @chneau can help us.

**Comment by chneau** [comment]
Hi @diavrank , unfortunately this is over my capabilities.

As far as I understand, since meteor is now using its own fork, https://github.com/meteor/node-fibers/ needs to publish binaries for different architectures that were (as said @GeoffreyBooth) manually uploaded by the original maintainer of node-fibers. 

So far I think we are missing the build steps for these binaries and some github action that uses https://github.com/mapbox/node-pre-gyp ?

For me, it's not clear either meteor/node-fibers or laverdet/node-fibers should do that

**Comment by GeoffreyBooth** [comment]
The Meteor team has addressed the Fibers issue in 2.5.6, which as been merged and will be on Docker Hub shortly. We won’t be able to support 2.5.1 through 2.5.5, but you should be able to upgrade from 2.5.0 to 2.5.6. See #100.

**Pull request closed without merging**
