### PR TITLE
Add 2.2

### PR DESCRIPTION
**Pull request by diavrank**
[Changelog](https://github.com/meteor/meteor/blob/devel/History.md)

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
Is there no version bump for Babel or anything else in `package.json`?

**Comment by diavrank** [comment]
Hello, no there isn't. I ran `npm update` and **package.json** was not updated.

**Comment by GeoffreyBooth** [comment]
> Hello, no there isn’t. I ran `npm update` and **package.json** was not altered.

Right but if you create a fresh Meteor project (e.g. from `meteor create`) the NPM package versions are the same as in the example project? They’re not using a newer version of Babel or anything?

**Comment by diavrank** [comment]
I have just created a new meteor app (in **v2.2**) and babel is on **7.11.2**, whereas the example in meteor-base is on **7.12.5**. So, I don't know if I have to downgrade babel of meteor-base to 7.11.2 (i don't think so)? 

The rest of dependencies are the same.

**Comment by GeoffreyBooth** [comment]
> I have just created a new meteor app (in **v2.2**) and babel is on **7.11.2**, whereas the example in meteor-base is on **7.12.5**. So, I don't know if I have to downgrade babel of meteor-base to 7.11.2 (i don't think so)?
> 
> The rest of dependencies are the same.

Okay, great! Thanks for checking.

**Pull request merged**
