### PR TITLE
Feat: Add 2.13.1 and 2.13.3

### PR DESCRIPTION
**Pull request by thiagotsn**
Changelog:

[2.13.1](https://github.com/meteor/meteor/blob/devel/docs/history.md#v2131-2023-09-04)
[2.13.3](https://github.com/meteor/meteor/blob/devel/docs/history.md#v2133-2023-09-08)

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
Thanks! Did you generate this via the `update.sh` script?

**Comment by thiagotsn** [comment]
Hi! Yes, I used the script, but I had to change manually the `meteor/node` path in the docker file because it was adding meteor/meteor/node...

**Comment by GeoffreyBooth** [comment]
Do you mind updating the script to fix that?

**Comment by GeoffreyBooth** [comment]
Probably better as a new PR. We can merge that in first, then you can run `update.sh` again and it should produce changes identical to this PR. That would confirm that the fix works, and that nothing was missed in this update.

**Comment by GeoffreyBooth** [comment]
Okay I’ve merged the other one, do you want to rebase this one and run `update.sh`?

**Comment by thiagotsn** [comment]
Sure, let me do that.

**Comment by thiagotsn** [comment]
Ok, that should be done now. It seems changes were the same.

**Pull request merged**
